fix: add PR source validation to Jenkinsfile
logdna/logdna-winston pull request #23
Opened 2020-10-26 16:52 UTC by mdeltito

Semver: patch
Ref: LOG-7713

2020-10-26 17:59 UTC, jakedipity approved these changes

2020-10-26 18:08 UTC, ligerzero459 requested changes

2020-10-26 18:08 UTC, ligerzero459 commented on Jenkinsfile
> +        , repo: REPO
Can you add `, branch: "master"` to the `versioner` blocks? The new version understands that and it'll set us up to change over to using `main` branch whenever we're ready

2020-10-27 13:20 UTC, darinspivey approved these changes

2020-10-27 14:59 UTC, ligerzero459 approved these changes

2020-10-27 15:11 UTC, merged