Always translate the log level
logdna/logdna-winston pull request #25
Opened 2020-12-11 13:07 UTC by mariocasciaro

Fixes the error "Invalid log level.  Using the default instead." produced when specifying the 'verbose' or 'http' log levels. Also add the 'debug' level mapping.

2020-12-15 16:08 UTC, darinspivey requested changes
Appreciate the corrections here!

2020-12-15 16:08 UTC, darinspivey commented on index.js
> +    const {level: ignored, message, indexMeta, timestamp, ...meta} = info
For clarity, we'd prefer the variable name to be `_` rather than `ignored`, since "ignored" could still some sort of functionality.

2020-12-15 16:08 UTC, darinspivey commented
@logdnabot please test this

2020-12-15 16:12 UTC, darinspivey commented on index.js
> +, ['debug', 'debug']
The linter is failing with trailing spaces on this line.  Please run `npm run test` prior to re-pushing anything.

2020-12-15 16:12 UTC, darinspivey commented on index.js
> +, ['debug', 'debug']
You can also run `npm run lint -- --fix` to auto-correct those issues

2020-12-16 17:44 UTC, darinspivey commented
If you rebase this onto origin, any lint or test errors will then show up in github checks

2020-12-17 10:54 UTC, mariocasciaro commented
Done

2020-12-17 12:57 UTC, darinspivey commented
@logdnabot please test this

2020-12-17 13:04 UTC, darinspivey approved these changes
Looks good, thanks for this update.

2020-12-17 13:15 UTC, jorgebay approved these changes
Thanks for the fix @mariocasciaro !

2020-12-17 13:19 UTC, merged

2020-12-17 13:22 UTC, mariocasciaro commented
👍 thank you